-
  name: 农业
  description: "<p class='sub-title'>种植业：</p>就其本质来说，种植业是以土地为重要生产资料，利用绿色植物，通过光合作用把自然界中的二氧化碳、水和矿物质合成有机物质，同时，把太阳能转化为化学能贮藏在有机物质中。它是一切以植物产品为食品的物质来源，也是人类生命活动的物质基础。种植业是大农业的重要基础。包括各种农作物、林木、果树、药用和观赏等植物的栽培。有粮食作物、经济作物、蔬菜作物、绿肥作物、饲料作物、牧草、花卉等园艺作物。在中国通常指粮、棉、油、糖、麻、丝、烟、茶、果、药、杂等作物的生产。亦指狭义的农业，在中国，种植业同林业、畜牧业、副业和渔业合在一起，为广义的农业。<p class='sub-title'>养殖业：</p>养殖业是利用畜禽等已经被人类驯化的动物，或者鹿、麝、狐、貂、水獭、鹌鹑等野生动物的生理机能，通过人工饲养、繁殖，使其将牧草和饲料等植物能转变为动物能，以取得肉、蛋、奶、羊毛、山羊绒、皮张、蚕丝和药材等禽畜。养殖业是农业的主要组成部分之一。与种植业并列为农业生产的两大支柱。主要包括牛、马、驴、骡、骆驼、猪、羊、鸡、鸭、鹅、兔、蜂 等家畜家禽饲养业和鹿、貂、水獭、麝等 野生经济动物驯养业。"
  tags: ["种植业", "养殖业"]
-
  name: 知识产权
  description: "<p class='sub-title'>知识产权领域认定：</p><ol><li>根据技术专家对本领域公知技术及相关专业技术的了解，并运用必要的检测、化验、分析手段，对被侵权的技术和相关技术的特征是否相同或者等同进行认定；</li><li>对技术转让合同标的是否成熟、实用，是否符合合同约定标准进行认定；</li><li>对技术开发合同履行失败是否属于风险责任进行认定；对技术咨询、技术服务以及其他各种技术合同履行结果是否符合合同约定，或者有关法定标准进行认定；</li><li>对技术秘密是否构成法定技术条件进行认定；</li><li>对其他知识产权诉讼中的技术争议进行认定。</li></ol><p>主要包括：专利权；商标权；著作权；工业品外观设计权；集成电路布图设计权；技术秘密和经营信息（不为公众所知悉）；植物新品种等</p>"
  tags: ["专利权", "商标权", "著作权", "工业品外观设计权", "集成电路布图设计权", "技术秘密和经营信息（不为公众所知悉）", "植物新品种"]
-
  name: 科技事务
  description: "<p class='sub-title'>水利：</p>用于控制和调配自然界的地表水和地下水，达到除害兴利目的而修建的工程。按其服务对象分为防洪工程、农田水利工程、水力发电工程、航道和港口工程、供水和排水工程、环境水利工程、海涂围垦工程等。可同时为防洪、供水、灌溉、发电等多种目标服务的水利工程，称为综合利用水利工程。水利工程需要修建坝、堤、溢洪道、水闸、进水口、渠道、渡漕、筏道、鱼道等不同类型的水工建筑物，以实现其目标。组成水利工程的基本组成是各种水工建筑物，包括挡水建筑物、泄水建筑物、进水建筑物和输水建筑物等。此外，还有专门为某一目的服务的水工建筑物，如专为河道整治、通航、过鱼、过木、水力发电、污水处理等服务的具有特殊功能的水工建筑物。水工建筑物以多种形式组合成不同类型的水利工程。<p class='sub-title'>电力：</p>电力系统是由发电厂、输电网、配电网和电力用户组成的整体。电力系统包括电力设施（如线路、电杆、变压器、总路漏保等）、电力设备（如断路器、隔离开关、电流互感器、电压互感器、母线、电抗器、电容器、变压器、配电柜等），以及保证安全可靠运行的继电保护装置、安全自动装置、调动自动化系统和电力通信等相应的辅助系统。"
  tags: ["水利", "电力"]
-
  name: 计算机
  description: "<p class='sub-title'>计算机领域定义：</p>计算机是对输入的各类信息，如数据、文字、图像、电信号等等，自动高效地进行加工处理并输出结果的电子装置。其范围包括：计算机硬件；计算机软件；计算机应用（包括：数值计算、数据处理、实时控制、计算机辅助设计、模式识别、娱乐及游戏）等。"
  tags: ["计算机硬件", "计算机软件", "数值计算", "数据处理", "实时控制", "计算机辅助设计", "模式识别", "娱乐及游戏"]
-
  name: 声像资料
  description: "<p class='sub-title'>声像资料领域定义：</p>包括对录音带、录像带、磁盘、光盘、图片等载体上记录的声音、图像信息的真实性、完整性及其所反映的情况过程进行的鉴定和对记录的声音、图像中的语言、人体、物体作出种类或者同一认定。"
  tags: ["声音鉴定", "图像鉴定", "人体鉴定", "物体鉴定"]
-
  name: 微量物证
  description: "<p class='sub-title'>微量物证领域认定：</p>是运用物理学、化学和仪器分析等科学方法，通过对有关物质材料的成分及其结构进行定性、定量分析，对检材的种类、检材和嫌疑样本的同类性和同一性进行鉴定。<p>常见鉴定内容：</p><ol><li>毒品、毒物、农药、生化毒剂、纸张、油墨、墨水、印油鉴定；</li><li>化妆品检验鉴定；</li><li>食品检验鉴定；</li><li>文化用品检验鉴定；</li><li>涂料检验鉴定；</li><li>金属、土壤检验鉴定；</li><li>生物检验鉴定；</li><li>爆炸、射击残留物检验鉴定；</li><li>塑料、橡胶制品检验鉴定；</li><li>建筑材料检验鉴定；</li><li>可疑未知物等的检验鉴定。</li></ol>"
  tags: ["毒品毒物鉴定", "化妆品鉴定", "食品鉴定", "文化用品鉴定", "涂料鉴定", "金属鉴定", "土壤鉴定", "生物鉴定", "爆炸和射击残留物鉴定", "塑料和橡胶制品鉴定", "建筑材料鉴定", "可疑未知物鉴定"]

